# Generated by Django 6.1.1 on 2026-09-30 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsession",
            name="athlete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sessions",
                to="club.athlete",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sessions",
                to="club.gym",
            ),
        ),
    ]
