# Generated by Django 6.1.2 on 2026-10-06 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_trainingsession_athletes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='athletes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'athlete'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
