# Generated by Django 6.1.1 on 2026-10-01 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0004_athlete_is_active_alter_coach_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsession",
            name="athlete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="club.athlete",
            ),
        ),
    ]
