# Generated by Django 6.1.1 on 2026-10-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0005_alter_trainingsession_athlete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingsession",
            name="athlete",
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="athletes",
            field=models.ManyToManyField(related_name="sessions", to="club.athlete"),
        ),
    ]
